name: ci
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  check-docs-and-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify files exist
        run: |
          test -f docs/Sections-4-10-Propagation-Edits.md
          test -f receipts/schema.sample.json
